/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Layout from "../Layout";
import Hero from "../Hero";
import MarketTrend from "../MarketTrend";
import Features from "../Features";
import CallToAction from "../CallToAction";
import MarketUpdate from "../MarketUpdate";
import GetStarted from "../GetStarted";
import LearnCrypto from "../LearnCrypto";

function Home() {
  return (
    <Layout>
      <Hero />
      <MarketTrend />
      <Features />
      <CallToAction />
      <MarketUpdate />
      <GetStarted />
      <LearnCrypto />
    </Layout>
  );
}

export default Home;
