/**
 * This code was generated by Builder.io.
 */
import React from "react";

function ArticleCard({ title, category, description, image }) {
  return (
    <article className="flex flex-col flex-1 shrink pb-4 rounded-2xl border border-solid basis-0 bg-white bg-opacity-0 border-white border-opacity-10 min-w-[240px]">
      <img
        loading="lazy"
        src={image}
        alt={title}
        className="object-contain w-full rounded-2xl aspect-[1.52]"
      />
      <div className="flex flex-col justify-center p-5 w-full">
        <div className="flex flex-col w-full">
          <div className="flex flex-col justify-center items-start pr-40 w-full text-xs font-medium max-md:pr-5">
            <div className="overflow-hidden gap-2.5 self-stretch px-1.5 rounded bg-white bg-opacity-10">
              {category}
            </div>
          </div>
          <h3 className="flex-1 shrink gap-2.5 self-stretch mt-3.5 w-full text-base font-semibold leading-6 text-white">
            {title}
          </h3>
          <p className="flex-1 shrink gap-2.5 mt-3.5 w-full text-sm text-zinc-400">
            {description}
          </p>
        </div>
      </div>
    </article>
  );
}

export default ArticleCard;
