/**
 * This code was generated by Builder.io.
 */
import React from "react";

function CallToAction() {
  return (
    <section className="flex overflow-hidden flex-wrap gap-10 justify-between items-center px-16 py-5 mt-32 w-full rounded-xl border border-solid border-white border-opacity-10 max-w-[1259px] max-md:px-5 max-md:mt-10 max-md:max-w-full">
      <div className="flex overflow-hidden flex-col self-stretch my-auto min-w-[240px] w-[536px] max-md:max-w-full">
        <h2 className="text-2xl font-semibold leading-none text-gray-100 max-md:max-w-full">
          New In Cryptocurrency?
        </h2>
        <p className="mt-3 text-lg leading-7 text-zinc-400 max-md:max-w-full">
          We'll tell you what cryptocurrencies are, how they work and why you
          should own one right now. So let's do it.
        </p>
      </div>
      <button className="overflow-hidden gap-2.5 self-stretch px-6 py-4 my-auto text-base font-semibold text-center text-white bg-teal-500 rounded-xl max-md:px-5">
        Learn & Explore Now
      </button>
    </section>
  );
}

export default CallToAction;
