/**
 * This code was generated by Builder.io.
 */
import React from "react";

function CryptoTableRow({
  id,
  name,
  symbol,
  price,
  change,
  marketStats,
  icon,
}) {
  return (
    <div className="flex overflow-hidden flex-wrap gap-10 justify-between items-center py-2.5 pr-2.5 pl-8 w-full border border-solid bg-white bg-opacity-0 border-white border-opacity-10 min-h-[62px] max-md:pl-5 max-md:max-w-full">
      <div className="flex flex-wrap justify-center items-center self-stretch my-auto text-base whitespace-nowrap min-w-[240px] text-zinc-400 max-md:max-w-full">
        <div className="overflow-hidden self-stretch py-1 pr-2.5 my-auto w-[74px]">
          {id}
        </div>
        <div className="flex gap-6 justify-center items-center self-stretch my-auto min-w-[240px]">
          <img
            loading="lazy"
            src={icon}
            alt={`${name} icon`}
            className="object-contain shrink-0 self-stretch my-auto w-11 aspect-square"
          />
          <div className="flex gap-3 items-center self-stretch my-auto min-w-[240px] w-[343px]">
            <div className="overflow-hidden self-stretch py-1 pr-2.5 my-auto">
              {name}
            </div>
            <div className="flex shrink-0 self-stretch my-auto w-px h-6 rounded-sm bg-stone-700" />
            <div className="overflow-hidden flex-1 shrink self-stretch py-1 pr-2.5 my-auto text-right min-w-[240px]">
              {symbol}
            </div>
          </div>
        </div>
      </div>
      <div className="flex flex-wrap justify-center items-center self-stretch my-auto min-w-[240px] max-md:max-w-full">
        <div className="overflow-hidden self-stretch py-1 pr-2.5 my-auto text-base whitespace-nowrap text-zinc-400 w-[189px]">
          {price}
        </div>
        <div className="overflow-hidden self-stretch py-1 pr-2.5 my-auto text-base whitespace-nowrap text-zinc-400 w-[162px]">
          {change}
        </div>
        <div className="flex overflow-hidden flex-col items-start self-stretch my-auto w-[215px]">
          <img
            loading="lazy"
            src={marketStats}
            alt={`${name} market stats`}
            className="object-contain aspect-[1.78] w-[71px]"
          />
        </div>
        <div className="flex overflow-hidden flex-col justify-center items-start self-stretch py-0.5 my-auto text-base font-semibold text-center text-white whitespace-nowrap w-[120px]">
          <button className="overflow-hidden gap-2.5 px-6 py-1 bg-teal-500 rounded-xl max-md:px-5">
            Trade
          </button>
        </div>
      </div>
    </div>
  );
}

export default CryptoTableRow;
