/**
 * This code was generated by Builder.io.
 */
import React from "react";

function CryptoCard({ name, fullName, price, change, icon, graph }) {
  return (
    <div className="flex overflow-hidden flex-col flex-1 shrink justify-center items-center py-5 pr-5 pl-5 rounded-2xl border border-solid basis-0 bg-white bg-opacity-0 border-white border-opacity-10 min-w-[240px]">
      <div className="flex gap-10 justify-between items-center w-full font-semibold max-w-[254px]">
        <div className="flex overflow-hidden gap-3.5 items-center self-stretch my-auto">
          <img
            loading="lazy"
            src={icon}
            alt={`${name} icon`}
            className="object-contain shrink-0 self-stretch my-auto aspect-square w-[50px]"
          />
          <div className="self-stretch my-auto text-lg text-gray-100">
            {name}
          </div>
          <div className="gap-2.5 self-stretch px-1.5 py-1 my-auto text-xs text-center text-gray-900 rounded bg-stone-300">
            {fullName}
          </div>
        </div>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/c041c993a8347495b55df516c2a3c9db215847dba657c9667cc66e0e147e42da?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196"
          alt="Graph icon"
          className="object-contain shrink-0 self-stretch my-auto w-12 aspect-square"
        />
      </div>
      <div className="flex self-stretch mt-4 w-full bg-gray-100 bg-opacity-10 min-h-[1px]" />
      <div className="flex gap-3 justify-between items-center mt-4 max-w-full font-medium w-[252px]">
        <div className="flex flex-col justify-center self-stretch my-auto w-[140px]">
          <div className="text-2xl text-gray-100">{price}</div>
          <div className="mt-2.5 text-lg leading-relaxed text-zinc-400">
            {change}
          </div>
        </div>
        <img
          loading="lazy"
          src={graph}
          alt={`${name} price graph`}
          className="object-contain shrink-0 self-stretch my-auto aspect-[1.85] w-[100px]"
        />
      </div>
    </div>
  );
}

export default CryptoCard;
