/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Footer() {
  return (
    <footer className="flex overflow-hidden flex-wrap gap-10 justify-between items-center self-stretch px-24 py-12 w-full min-h-[297px] max-md:px-5 max-md:max-w-full">
      <div className="flex flex-col self-stretch my-auto min-w-[240px] w-[287px]">
        <div className="flex flex-col items-start w-full text-2xl font-bold text-teal-500">
          <div className="flex-1 shrink gap-2.5 self-stretch py-px max-w-full min-h-[30px] w-[133px]">
            Crypto<span className="text-teal-500">Cap</span>
          </div>
        </div>
        <div className="flex flex-col mt-16 w-full max-w-[287px] max-md:mt-10">
          <div className="flex gap-3 justify-between items-center max-w-full w-[132px]">
            <a href="#" aria-label="Facebook">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/1383a7f651dfe6615330833d2b5ededd4e259c019d9de90d079e8ec1a283d9a3?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196"
                alt=""
                className="object-contain shrink-0 self-stretch my-auto w-6 aspect-square"
              />
            </a>
            <a href="#" aria-label="Twitter">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/d83e0192a8e4fc424aaaa775a99b5dd6a1768cc62641a834df14087565f77481?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196"
                alt=""
                className="object-contain shrink-0 self-stretch my-auto w-6 aspect-square"
              />
            </a>
            <a href="#" aria-label="Instagram">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/9b48a0431eb8cec2b5b2b6d873a3450d5c03537503ab1a48a3b9e8d8d8519347?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196"
                alt=""
                className="object-contain shrink-0 self-stretch my-auto w-6 aspect-square"
              />
            </a>
            <a href="#" aria-label="YouTube">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/3ad50acc247f960e7b8c3a77590ec39316fc561b673fabb1c2f6257d7d541a31?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196"
                alt=""
                className="object-contain shrink-0 self-stretch my-auto w-6 aspect-square"
              />
            </a>
          </div>
          <p className="gap-2.5 mt-8 w-full text-base text-zinc-400">
            2021 CoinMarketCap. All rights reserved
          </p>
        </div>
      </div>
      <div className="flex flex-wrap gap-10 justify-between items-start self-stretch my-auto min-w-[240px] w-[732px] max-md:max-w-full">
        <div className="flex overflow-hidden flex-col w-[137px]">
          <h3 className="gap-2.5 self-stretch w-full text-lg font-semibold leading-none text-gray-100">
            About Us
          </h3>
          <nav className="flex flex-col mt-5 w-full text-base text-zinc-400">
            <a
              href="#"
              className="gap-2.5 self-stretch w-full whitespace-nowrap"
            >
              About
            </a>
            <a
              href="#"
              className="gap-2.5 self-stretch mt-5 w-full whitespace-nowrap"
            >
              Careers
            </a>
            <a
              href="#"
              className="gap-2.5 self-stretch mt-5 w-full whitespace-nowrap"
            >
              Blog
            </a>
            <a href="#" className="gap-2.5 self-stretch mt-5 w-full">
              Legal & privacy
            </a>
          </nav>
        </div>
        <div className="flex overflow-hidden flex-col w-[149px]">
          <h3 className="flex-1 shrink gap-2.5 self-stretch w-full text-lg font-semibold leading-none text-gray-100 whitespace-nowrap">
            Services
          </h3>
          <nav className="flex flex-col mt-5 w-full text-base max-w-[149px] text-zinc-400">
            <a
              href="#"
              className="gap-2.5 self-stretch w-full whitespace-nowrap"
            >
              Applications
            </a>
            <a href="#" className="gap-2.5 self-stretch mt-5 w-full">
              Buy Crypto
            </a>
            <a
              href="#"
              className="gap-2.5 self-stretch mt-5 w-full whitespace-nowrap"
            >
              Affiliate
            </a>
            <a href="#" className="gap-2.5 self-stretch mt-5 w-full">
              Institutional Services
            </a>
          </nav>
        </div>
        <div className="flex overflow-hidden flex-col w-[168px]">
          <h3 className="flex-1 shrink gap-2.5 self-stretch w-full text-lg font-semibold leading-none text-gray-100 whitespace-nowrap">
            Learn
          </h3>
          <nav className="flex flex-col mt-5 w-full text-base max-w-[168px] text-zinc-400">
            <a href="#" className="gap-2.5 self-stretch w-full">
              What is Cryptocurrency?
            </a>
            <a href="#" className="gap-2.5 self-stretch mt-5 w-full">
              Crypto Basic
            </a>
            <a href="#" className="gap-2.5 self-stretch mt-5 w-full">
              Tips and Tutorials
            </a>
            <a href="#" className="gap-2.5 self-stretch mt-5 w-full">
              Market Update
            </a>
          </nav>
        </div>
      </div>
    </footer>
  );
}

export default Footer;
