/**
 * This code was generated by Builder.io.
 */
import React from "react";
import GetStartedStep from "./GetStartedStep";

const steps = [
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/5498e812c89c59c137f18ce35aadb5f1c7dca5f519de5ad7b691792bee2f3dbe?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196",
    title: "Create Your Account",
    description: "Your account and personal identity are guaranteed safe.",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/78eb00cfdc3246e6569a2cb738321ad5850c8759225f3f32cb68611287278c58?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196",
    title: "Connect Bank Account",
    description: "Connect the bank account to start transactions.",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/6ef0688cdb0f776127aee17f37f78cd1e9320ed01486f08309c7878832d3abfe?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196",
    title: "Start Build Portfolio",
    description: "Buy and sell popular currencies and keep track of them.",
  },
];

function GetStarted() {
  return (
    <section className="flex flex-wrap gap-10 items-start mt-32 w-full max-w-[1257px] max-md:mt-10 max-md:max-w-full">
      <div className="flex flex-col flex-1 shrink basis-0 min-w-[240px] max-md:max-w-full">
        <div className="flex overflow-hidden flex-col justify-center w-full max-md:max-w-full">
          <h2 className="flex-1 shrink gap-2.5 py-2.5 pr-2.5 w-full text-4xl font-bold leading-none text-gray-100 max-md:max-w-full">
            How To Get Started
          </h2>
          <p className="flex-1 shrink gap-2.5 py-2.5 pr-2.5 mt-2 w-full text-lg leading-7 text-zinc-400 max-md:max-w-full">
            Simple and easy way to start your investment <br /> in
            cryptocurrency
          </p>
        </div>
        <div className="flex flex-col justify-center items-start pr-80 mt-10 w-full text-base font-semibold text-center text-white max-md:pr-5 max-md:max-w-full">
          <button className="overflow-hidden gap-2.5 self-stretch px-6 py-3.5 max-w-full bg-teal-500 rounded-xl w-[190px] max-md:px-5">
            Get Started
          </button>
        </div>
      </div>
      <div className="flex flex-col flex-1 shrink basis-0 min-h-[430px] min-w-[240px] max-md:max-w-full">
        {steps.map((step, index) => (
          <GetStartedStep key={index} {...step} />
        ))}
      </div>
    </section>
  );
}

export default GetStarted;
