/**
 * This code was generated by Builder.io.
 */
import React from "react";

function GetStartedStep({ icon, title, description }) {
  return (
    <div className="flex overflow-hidden flex-wrap flex-1 gap-5 items-center pt-2.5 pr-14 pb-5 pl-5 mt-6 rounded-2xl border border-solid bg-white bg-opacity-0 border-white border-opacity-10 size-full max-md:pr-5 max-md:max-w-full">
      <div className="flex gap-2.5 items-start self-stretch my-auto w-20">
        <img
          loading="lazy"
          src={icon}
          alt={`${title} icon`}
          className="object-contain w-20 aspect-square"
        />
      </div>
      <div className="flex flex-col flex-1 shrink self-stretch my-auto basis-0 min-w-[240px]">
        <h3 className="overflow-hidden flex-1 shrink gap-2.5 p-2.5 w-full text-xl font-semibold text-gray-100">
          {title}
        </h3>
        <p className="overflow-hidden flex-1 shrink gap-2.5 self-stretch px-2.5 w-full text-base text-zinc-400">
          {description}
        </p>
      </div>
    </div>
  );
}

export default GetStartedStep;
