/**
 * This code was generated by Builder.io.
 */
import React from "react";

function GetStartedStep({ icon, title, description }) {
  return (
    <div className="flex justify-center  overflow-hidden  gap-5 space-y-8 items-center  rounded-2xl border border-solid bg-white bg-opacity-0 border-white border-opacity-10 ">
      <div className="flex items-center justify-center">
        <img
          loading="lazy"
          src={icon}
          alt={`${title} icon`}
          className="object-contain w-20 aspect-square"
        />
        <h3 className="overflow-hidden  w-full text-xl font-semibold text-gray-100">
          {title}
        </h3>
        <p className="overflow-hidden flex-1 w-full text-base text-zinc-400">
          {description}
        </p>
      </div>
      <div className="flex flex-col flex-1 ">
      </div>
    </div>
  );
}

export default GetStartedStep;
