/**
 * This code was generated by Builder.io.
 */
import React from "react";
import LanguageSelector from "./LanguageSelector";

function Header() {
  return (
    <header className="flex overflow-hidden flex-wrap gap-10 justify-center items-center self-stretch px-24 w-full text-base min-h-[90px] max-md:px-5 max-md:max-w-full">
      <div className="grow shrink gap-2.5 self-stretch py-px my-auto text-2xl font-bold text-teal-500 min-h-[30px] w-[164px]">
        Crypto<span className="text-teal-500">Cap</span>
      </div>
      <nav className="flex overflow-hidden gap-5 items-start self-stretch my-auto font-medium text-gray-100 whitespace-nowrap min-w-[240px] max-md:max-w-full">
        <a
          href="#"
          className="gap-2.5 self-stretch p-2.5 font-semibold text-teal-500 min-h-[39px]"
        >
          Home
        </a>
        <a href="#" className="gap-2.5 self-stretch p-2.5 min-h-[39px]">
          Businesses
        </a>
        <a href="#" className="gap-2.5 self-stretch p-2.5 min-h-[39px]">
          Trade
        </a>
        <a href="#" className="gap-2.5 self-stretch p-2.5 min-h-[39px]">
          Market
        </a>
        <a href="#" className="gap-2.5 self-stretch p-2.5 min-h-[39px]">
          Learn
        </a>
      </nav>
      <div className="flex grow shrink gap-5 justify-between items-center self-stretch my-auto font-semibold text-center whitespace-nowrap w-[164px]">
        <LanguageSelector />
        <button className="overflow-hidden gap-2.5 self-stretch px-6 py-3.5 my-auto text-white bg-teal-500 rounded-xl w-[104px] max-md:px-5">
          Login
        </button>
      </div>
    </header>
  );
}

export default Header;
