/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Hero() {
  return (
    <section className="flex flex-col justify-center mt-24 max-w-full text-center w-[788px] max-md:mt-10">
      <div className="flex flex-col justify-center w-full max-md:max-w-full">
        <h1 className="flex-1 shrink gap-2.5 p-2.5 w-full text-4xl font-bold leading-none text-gray-100 max-md:max-w-full">
          Start and Build Your Crypto Portfolio Here
        </h1>
        <p className="flex-1 shrink gap-2.5 p-2.5 mt-2 w-full text-lg leading-7 text-zinc-400 max-md:max-w-full">
          Only at CryptoCap, you can build a good portfolio and learn <br />{" "}
          best practices about cryptocurrency.
        </p>
      </div>
      <button className="overflow-hidden gap-2.5 self-center px-6 py-4 mt-10 max-w-full text-base font-semibold text-white bg-teal-500 rounded-xl w-[190px] max-md:px-5">
        Get Started
      </button>
    </section>
  );
}

export default Hero;
