/**
 * This code was generated by Builder.io.
 */
import React from "react";

function LanguageSelector() {
  return (
    <div className="flex overflow-hidden gap-2.5 items-start self-stretch my-auto text-zinc-400">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/331cceac02e5c062f51402e5678beb45b7f2d89880478f90343dfe78a987e240?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196"
        alt=""
        className="object-contain shrink-0 w-6 aspect-square"
      />
      <div className="flex justify-center items-center w-[46px]">
        <div className="flex-1 shrink self-stretch my-auto basis-0">EN</div>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/a7c7c5bea9433a35464fb855994c3186a06460493e193ab1faf3c0968d19ef51?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196"
          alt=""
          className="object-contain flex-1 shrink self-stretch my-auto aspect-[0.96] basis-0 w-[23px]"
        />
      </div>
    </div>
  );
}

export default LanguageSelector;
