/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import Footer from "./Footer";
import AnimatedBackground from "./AnimatedBackground";

function Layout({ children }) {
  return (
    <div className="flex overflow-hidden flex-col items-center w-full">
      <AnimatedBackground />
      <Header />
      <main className="flex flex-col items-center w-full   px-4 lg:px-32 z-30">
        {children}
      </main>
      <Footer />
    </div>
  );
}

export default Layout;
