/**
 * This code was generated by Builder.io.
 */
import React from "react";
import CryptoCard from "./CryptoCard";

const cryptoData = [
  {
    name: "BTC",
    fullName: "BITCOIN",
    price: "$56,623.54",
    change: "1.41%",
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/53d47b92dd89f242932c9a7d42a60824bea17762c478e7db077784ced305b4fc?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196",
    graph:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/65b29b128753f5105f5903d40355357a3cdeb8f70518cd4b730d9174e1c0f84f?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196",
  },
  {
    name: "ETH",
    fullName: "ETHEREUM",
    price: "$4,267.90",
    change: "2.22%",
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/203d940ba82a9c50b27bafe5e57e7ac7bd31d1c1afd7b38e496888c257859aed?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196",
    graph:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/0ff3bb0f3b3f86cfe76e4cc81a14a6b24ad98078b102fcc8f14944891231afe3?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196",
  },
  {
    name: "BNB",
    fullName: "BINANCE",
    price: "$587.74",
    change: "0.82%",
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/601ebf9af93f1808c88730f1a2a972e8ca7efc7f6352ea18102268aa51cb71c2?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196",
    graph:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/1d3b8c7d83a8a80c1b8769a901098b13e0cb812d78ce8df94e7e26e9314e03b6?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196",
  },
  {
    name: "USDT",
    fullName: "TETHER",
    price: "$0.9998",
    change: "0,03%",
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/3057321d999aae2f969cdc1e544a0aa436f8a5eb21a46e1d977d5f9c42ad1fe7?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196",
    graph:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/29946762711df1df79161cff5580c2356ea59615ff8eb837721db6f98637f6d9?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196",
  },
];

function MarketTrend() {
  return (
    <section className="flex flex-col justify-between mt-36 w-full max-w-[1260px] min-h-[243px] max-md:mt-10 max-md:max-w-full">
      <h2 className="flex-1 shrink gap-2.5 w-full text-2xl font-semibold leading-none text-gray-100 max-md:max-w-full">
        Market Trend
      </h2>
      <div className="flex flex-wrap gap-6 mt-6 w-full whitespace-nowrap max-md:max-w-full">
        {cryptoData.map((crypto, index) => (
          <CryptoCard key={index} {...crypto} />
        ))}
      </div>
    </section>
  );
}

export default MarketTrend;
