/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import CryptoTableRow from './CryptoTableRow';

const cryptoData = [
  { id: 1, name: 'Bitcoin', symbol: 'BTC', price: '$56,623.54', change: '1.41%', marketStats: 'https://cdn.builder.io/api/v1/image/assets/TEMP/abdb763624db8101e052b3aa473bb554090382b3463584514dc2e47e3cb40032?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196', icon: 'https://cdn.builder.io/api/v1/image/assets/TEMP/cdc24f701369fe8609f85c5ac9736ee83f68cf34b756cf00d2baf5d2faab1e41?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196' },
  
  { id: 2, name: 'Ethereum', symbol: 'ETH', price: '$4,267.90', change: '2.22%', marketStats: 'https://cdn.builder.io/api/v1/image/assets/TEMP/5fba483fa0425a2d07aa68a1568264890ac0e593bf9514ae413bd74fe28fe3d3?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196', icon: 'https://cdn.builder.io/api/v1/image/assets/TEMP/5d2e3f7119ce4fdf376c984a9fbcfb47124287f30a1d4c425a4cac341f09b8da?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196' },
  { id: 3, name: 'Binance', symbol: 'BNB', price: '$587.74', change: '-0.82%', marketStats: 'https://cdn.builder.io/api/v1/image/assets/TEMP/a18c10e1aaa84e09232e9334a9ae61eba9398ea1487ee9e0669093b58fd8b6af?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196', icon: 'https://cdn.builder.io/api/v1/image/assets/TEMP/ca695a26f8860e3e05eb142153155f01d71cc0e971a077b3e6d83c3060e0dbf9?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196' },
  { id: 4, name: 'Tether', symbol: 'USDT', price: '$0.9998', change: '-0.03%', marketStats: 'https://cdn.builder.io/api/v1/image/assets/TEMP/820b83b851fb0854832577ce51480e559887fa2a523bd70f5ebadc11f85d9e3d?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196', icon: 'https://cdn.builder.io/api/v1/image/assets/TEMP/aca0955710819f2eee4d1176cba96aec1ee2f634143f65de0d9336cd069f7c24?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196' },
  { id: 5, name: 'Solana', symbol: 'SOL', price: '$213.67', change: '-0.53%', marketStats: 'https://cdn.builder.io/api/v1/image/assets/TEMP/a973e5626e9511c6c664407d9b32b4163ed7b52ee445c370dada8c8ec659c776?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196', icon: 'https://cdn.builder.io/api/v1/image/assets/TEMP/e4a4e27c9e9272a307ba91bcd88e3e5823712394cfe3bee2e63c1ecee09a5535?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196' },
  { id: 6, name: 'XRP', symbol: 'XRP', price: '$1.04', change: '-0.44%', marketStats: 'https://cdn.builder.io/api/v1/image/assets/TEMP/58d703cd4c7b4a4fb8fd7cb5645f85c1cbf8060139fc91e3242b7e479ba40978?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196', icon: 'https://cdn.builder.io/api/v1/image/assets/TEMP/c56c34c8db11fc2e54ef20346b0d4f7d321224b07575dec22c1a1fad914de2ea?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196' },
  { id: 7, name: 'USD Coin', symbol: 'USDC', price: '$1.00', change: '-0.03%', marketStats: 'https://cdn.builder.io/api/v1/image/assets/TEMP/22511f14373abeb608a7b687fc8df0cc627308f5b0711602a6c10ca4086e8405?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196', icon: 'https://cdn.builder.io/api/v1/image/assets/TEMP/fdd9db4f8401c5525322aadb618687d3c72d657040edaf2fc81a67f9fd619a18?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196' },
];

function MarketUpdate() {
  return (
    <section className="flex flex-col mt-60 w-full max-w-[1261px] max-md:mt-10 max-md:max-w-full">
      <p className="z-10 text-lg font-medium leading-relaxed text-zinc-400 max-md:max-w-full">
        Cryptocurrency Categories
      </p>
      <h2 className="flex-1 shrink gap-2.5 w-full text-4xl font-bold leading-none text-gray-100 max-md:max-w-full">
        Market Update
      </h2>
      <div className="flex flex-col mt-8 w-full text-base text-zinc-400 max-md:max-w-full">
        <div className="flex flex-wrap gap-10 justify-between items-center w-full max-md:max-w-full">
          <div className="flex flex-wrap gap-3 items-center self-stretch my-auto min-w-[240px] max-md:max-w-full">
            <button className="overflow-hidden gap-2.5 self-stretch px-3 py-2.5 my-auto font-medium text-gray-900 whitespace-nowrap bg-gray-200 rounded-md">
              Popular
            </button>
            <button className="overflow-hidden gap-2.5 self-stretch px-3 py-2.5 my-auto whitespace-nowrap rounded-md border border-solid bg-white bg-opacity-10 border-white border-opacity-10">
              Metaverse
            </button>
            <button className="overflow-hidden gap-2.5 self-stretch px-3 py-2.5 my-auto whitespace-nowrap rounded-md border border-solid bg-white bg-opacity-10 border-white border-opacity-10">
              Entertainment
            </button>
            <button className="overflow-hidden gap-2.5 self-stretch px-3 py-2.5 my-auto whitespace-nowrap rounded-md border border-solid bg-white bg-opacity-10 border-white border-opacity-10">
              Energy
            </button>
            <button className="overflow-hidden gap-2.5 self-stretch px-3 py-2.5 my-auto whitespace-nowrap rounded-md border border-solid bg-white bg-opacity-10 border-white border-opacity-10">
              Gaming
            </button>
            <button className="overflow-hidden gap-2.5 self-stretch px-3 py-2.5 my-auto whitespace-nowrap rounded-md border border-solid bg-white bg-opacity-10 border-white border-opacity-10">
              Music
            </button>
            <button className="overflow-hidden gap-2.5 self-stretch px-3 py-2.5 my-auto rounded-md border border-solid bg-white bg-opacity-10 border-white border-opacity-10">
              See All 12+
            </button>
          </div>
          <div className="flex overflow-hidden flex-col justify-center items-start self-stretch p-2.5 my-auto bg-gray-900 rounded-md border border-solid border-white border-opacity-10 min-w-[240px] w-[282px]">
            <div className="flex gap-4 justify-center items-center">
              <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/79db729de9585fb38ca5c1b9320130c8f586815fd8a74068cb7cd52ab4294d79?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196" alt="" className="object-contain shrink-0 self-stretch my-auto w-6 aspect-square" />
              <input type="text" placeholder="Search Coin" className="self-stretch my-auto bg-transparent border-none text-white focus:outline-none" />
            </div>
          </div>
        </div>
      </div>
      <div className="flex flex-col mt-8 w-full max-md:max-w-full">
        <div className="flex overflow-hidden flex-wrap gap-10 justify-between items-center py-6 pr-20 pl-8 w-full text-base font-medium rounded border border-solid bg-white bg-opacity-0 border-white border-opacity-10 min-h-[62px] text-zinc-400 max-md:px-5 max-md:max-w-full">
          <div className="flex gap-10 items-start self-stretch my-auto whitespace-nowrap">
            <div className="gap-2.5 self-stretch pr-2.5">NO</div>
            <div className="gap-2.5 self-stretch pr-2.5">NAME</div>
          </div>
          <div className="flex flex-wrap gap-10 items-start self-stretch my-auto min-w-[240px] max-md:max-w-full">
            <div className="gap-2.5 self-stretch pr-2.5">LAST PRICE</div>
            <div className="gap-2.5 self-stretch pr-2.5 whitespace-nowrap">CHANGE</div>
            <div className="gap-2.5 self-stretch pr-2.5">MARKET STATS</div>
            <div className="gap-2.5 self-stretch pr-2.5 whitespace-nowrap">TRADE</div>
          </div>
        </div>
        {cryptoData.map((crypto) => (
          <CryptoTableRow key={crypto.id} {...crypto} />
        ))}
      </div>
      <button className="flex-1 shrink gap-2.5 self-stretch py-2.5 pr-2.5 mt-8 w-full text-base font-semibold text-teal-500 underline max-md:max-w-full">
        See All Coins
      </button>
    </section>
  );
}

export default MarketUpdate;